name: CI-CD ECR Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 306719643101.dkr.ecr.us-east-1.amazonaws.com

      # ✅ FIXED: build from webapp folder
      - name: Build Docker Image
        run: docker build -t webapp ./webapp

      - name: Tag Docker Image
        run: |
          docker tag webapp:latest 306719643101.dkr.ecr.us-east-1.amazonaws.com/webapp:latest

      - name: Push to ECR
        run: |
          docker push 306719643101.dkr.ecr.us-east-1.amazonaws.com/webapp:latest


  deploy:
    runs-on: self-hosted
    needs: build-push

    steps:
      # ❗ IMPORTANT: checkout needed if using docker-compose.yml
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 306719643101.dkr.ecr.us-east-1.amazonaws.com

      - name: Pull latest image
        run: |
         sudo  docker pull 306719643101.dkr.ecr.us-east-1.amazonaws.com/webapp:latest

      #  SIMPLE deploy 
      - name: Run container
        run: |
          sudo docker stop webapp || true
          sudo docker rm webapp || true
          sudo docker run -d -p 80:3000 --name webapp \
            306719643101.dkr.ecr.us-east-1.amazonaws.com/webapp:latest

